<template>
  <div>
    <!-- Social Links -->
    <div class="footer">
      <div class="wrapper">
        <a class="icon github" href="https://github.com/ugnjhjf">
          <div class="tooltip">Github</div>
          <span><i class="fab fa-github"></i></span>
        </a>

        <a class="icon instagram" href="https://www.instagram.com/rokidna?igsh=bHR4a2s5dmhicTln&utm_source=qr">
          <div class="tooltip">Instagram</div>
          <span><i class="fab fa-instagram"></i></span>
        </a>
        
        <a class="icon weixin" href="https://u.wechat.com/EINIdt19g0KhFBMg6ONz7LE">
          <div class="tooltip">Wechat</div>
          <span><i class="fab fa-weixin"></i></span>
        </a>
        
        <a class="icon linkedin" href="https://www.linkedin.com/in/david-shum-181595267/">
          <div class="tooltip">Linkedin</div>
          <span><i class="fab fa-linkedin"></i></span>
        </a>
      </div>
    </div>
    
    <!-- Copyright Information -->
    <div class="footer footer-rokidna">
      <ul>
        <li><span>Rokidna G | Made with </span><span class="heart">❤</span></li>
        <li><span>Background images are generated by stable diffusion.</span></li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Footer'
}
</script>
